# Generated by Django 2.0 on 2017-12-13 10:32

import catalog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171213_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/media/'), upload_to=catalog.models.image_directory_path),
        ),
    ]
