# Generated by Django 2.0 on 2017-12-13 10:47

import catalog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20171213_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/images//media/', location='C:\\wamp64\\www\\library\\media/media/'), upload_to=catalog.models.image_directory_path),
        ),
    ]
