# Generated by Django 2.0 on 2017-12-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20171213_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='photo',
        ),
    ]
