# Generated by Django 2.0 on 2017-12-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20171213_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='photo',
            new_name='image',
        ),
    ]
