# Generated by Django 2.0 on 2017-12-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20171214_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='book',
        ),
        migrations.AddField(
            model_name='boutique',
            name='book',
            field=models.ManyToManyField(blank=True, to='catalog.Book'),
        ),
    ]
