# Generated by Django 2.0 on 2017-12-15 14:14

import catalog.admin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20171215_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
