# Generated by Django 2.0.1 on 2018-01-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0030_auto_20171215_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='panier',
            name='product',
            field=models.ManyToManyField(blank=True, to='catalog.Book'),
        ),
        migrations.AddField(
            model_name='panier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
