# Generated by Django 2.0.1 on 2018-01-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_remove_panier_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='quantity',
        ),
    ]
