# Generated by Django 2.0.1 on 2018-01-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_remove_panier_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='PanierItem',
        ),
    ]
